name: "Prow github actions"
on:
  issue_comment:
    types: [ created ]
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: chnsz/prow-github-actions@v1.0.0
        if: ${{ github.repository == 'g42cloud-terraform/terraform-provider-g42cloud' }}
        with:
          prow-commands: |
            /assign
            /unassign
            /approve
            /retitle
            /area
            /kind
            /priority
            /remove
            /lgtm
            /close
            /reopen
            /lock
            /milestone
            /hold
            /cc
            /uncc
          github-token: "${{ secrets.ROBOT_PAT }}"
